In [1]:
import pandas as pd

data = pd.read_json(r'D:\專案\Projects\Youtube channel analysis\url_list.json')

df = pd.DataFrame(data)

df

                                                   urls
0     https://www.youtube.com/watch?v=AmE821Lz8wg&li...
1     https://www.youtube.com/watch?v=4YY3hda8rq4&li...
2     https://www.youtube.com/watch?v=Q2DGwesYFQU&li...
3     https://www.youtube.com/watch?v=XQWT6GvxP_s&li...
4     https://www.youtube.com/watch?v=SpOg0A_nNjs&li...
...                                                 ...
1045        https://www.youtube.com/watch?v=QKRATfEu2ng
1046        https://www.youtube.com/watch?v=LyNBg-_5KQI
1047        https://www.youtube.com/watch?v=wqnK0ekscdw
1048        https://www.youtube.com/watch?v=OR_uz02pBQM
1049                                               None

[1050 rows x 1 columns]

In [2]:
df.fillna(0, inplace=True)
print(df)
print(df.dtypes)

                                                   urls
0     https://www.youtube.com/watch?v=AmE821Lz8wg&li...
1     https://www.youtube.com/watch?v=4YY3hda8rq4&li...
2     https://www.youtube.com/watch?v=Q2DGwesYFQU&li...
3     https://www.youtube.com/watch?v=XQWT6GvxP_s&li...
4     https://www.youtube.com/watch?v=SpOg0A_nNjs&li...
...                                                 ...
1045        https://www.youtube.com/watch?v=QKRATfEu2ng
1046        https://www.youtube.com/watch?v=LyNBg-_5KQI
1047        https://www.youtube.com/watch?v=wqnK0ekscdw
1048        https://www.youtube.com/watch?v=OR_uz02pBQM
1049                                                  0

[1050 rows x 1 columns]
urls    object
dtype: object

In [3]:
df_nonull = df.dropna()

print(df_nonull)
print(df_nonull.dtypes)

                                                   urls
0     https://www.youtube.com/watch?v=AmE821Lz8wg&li...
1     https://www.youtube.com/watch?v=4YY3hda8rq4&li...
2     https://www.youtube.com/watch?v=Q2DGwesYFQU&li...
3     https://www.youtube.com/watch?v=XQWT6GvxP_s&li...
4     https://www.youtube.com/watch?v=SpOg0A_nNjs&li...
...                                                 ...
1045        https://www.youtube.com/watch?v=QKRATfEu2ng
1046        https://www.youtube.com/watch?v=LyNBg-_5KQI
1047        https://www.youtube.com/watch?v=wqnK0ekscdw
1048        https://www.youtube.com/watch?v=OR_uz02pBQM
1049                                                  0

[1050 rows x 1 columns]
urls    object
dtype: object

In [4]:
df_nodouble = df_nonull.drop_duplicates()
df_nodouble

                                                   urls
0     https://www.youtube.com/watch?v=AmE821Lz8wg&li...
1     https://www.youtube.com/watch?v=4YY3hda8rq4&li...
2     https://www.youtube.com/watch?v=Q2DGwesYFQU&li...
3     https://www.youtube.com/watch?v=XQWT6GvxP_s&li...
4     https://www.youtube.com/watch?v=SpOg0A_nNjs&li...
...                                                 ...
1044        https://www.youtube.com/watch?v=rft3_qNyyUI
1045        https://www.youtube.com/watch?v=QKRATfEu2ng
1046        https://www.youtube.com/watch?v=LyNBg-_5KQI
1047        https://www.youtube.com/watch?v=wqnK0ekscdw
1048        https://www.youtube.com/watch?v=OR_uz02pBQM

[786 rows x 1 columns]

In [5]:
# Assuming you have a DataFrame named df
column_name = df_nodouble.columns[0]
print(column_name)

urls

In [6]:
df_final = df_nodouble[df_nodouble['urls'].str.contains('list=UULFmsX3g', na=False)]
df_final

                                                   urls
0     https://www.youtube.com/watch?v=AmE821Lz8wg&li...
1     https://www.youtube.com/watch?v=4YY3hda8rq4&li...
2     https://www.youtube.com/watch?v=Q2DGwesYFQU&li...
3     https://www.youtube.com/watch?v=XQWT6GvxP_s&li...
4     https://www.youtube.com/watch?v=SpOg0A_nNjs&li...
...                                                 ...
1024  https://www.youtube.com/watch?v=YLluDLBU2Hs&li...
1025  https://www.youtube.com/watch?v=tQ0ctr-ar1k&li...
1026  https://www.youtube.com/watch?v=4sSDLYH9aV8&li...
1027  https://www.youtube.com/watch?v=AipWa1ZXPlw&li...
1028  https://www.youtube.com/watch?v=FPzZRppnfU8&li...

[668 rows x 1 columns]

In [7]:
df_reset = df_final.reset_index(drop=True)
df_reset

                                                  urls
0    https://www.youtube.com/watch?v=AmE821Lz8wg&li...
1    https://www.youtube.com/watch?v=4YY3hda8rq4&li...
2    https://www.youtube.com/watch?v=Q2DGwesYFQU&li...
3    https://www.youtube.com/watch?v=XQWT6GvxP_s&li...
4    https://www.youtube.com/watch?v=SpOg0A_nNjs&li...
..                                                 ...
663  https://www.youtube.com/watch?v=YLluDLBU2Hs&li...
664  https://www.youtube.com/watch?v=tQ0ctr-ar1k&li...
665  https://www.youtube.com/watch?v=4sSDLYH9aV8&li...
666  https://www.youtube.com/watch?v=AipWa1ZXPlw&li...
667  https://www.youtube.com/watch?v=FPzZRppnfU8&li...

[668 rows x 1 columns]

In [8]:
df_reset.to_json(r'url_list_cleaned.json', indent=1)